# Generated by Django 2.2.16 on 2022-08-16 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_auto_20220815_1801'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='no_self_user',
        ),
    ]
